<?php

namespace Pagomio\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * marksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marksRepository extends EntityRepository
{
}
