<?php

namespace Pagomio\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * payment_methodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class payment_methodsRepository extends EntityRepository
{
}
