<?php

namespace Pagomio\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * payment_methods_has_marksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class payment_methods_has_marksRepository extends EntityRepository
{
}
